package algorithmvisualization.view;

import algorithmvisualization.HelperMethods;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 * @author Murat AKIN
 */
public class FillPanel extends javax.swing.JPanel {

    Dimension scrSize;
    ToolPanel toolPanel;
    
    /**
     * Creates new form Dialog
     */
    public FillPanel(ToolPanel toolPanel) {
        initComponents();

        this.toolPanel = toolPanel;
        
        scrSize = Toolkit.getDefaultToolkit().getScreenSize();
    }

    public void clearInputValues() {
        xFromTextField.setText("");
        xToTextField.setText("");
        yFromTextField.setText("");
        yToTextField.setText("");
        numberTextField.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        shapeTypeLabel = new javax.swing.JLabel();
        xLabel = new javax.swing.JLabel();
        yLabel = new javax.swing.JLabel();
        xFromLabel = new javax.swing.JLabel();
        yFromLabel = new javax.swing.JLabel();
        xFromTextField = new javax.swing.JTextField();
        yFromTextField = new javax.swing.JTextField();
        xToLabel = new javax.swing.JLabel();
        yToLabel = new javax.swing.JLabel();
        xToTextField = new javax.swing.JTextField();
        yToTextField = new javax.swing.JTextField();
        pointRadioButton = new javax.swing.JRadioButton();
        clusterRadioButton = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        numberTextField = new javax.swing.JTextField();
        generateButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(321, 189));

        shapeTypeLabel.setText("Shape Type:");

        xLabel.setText("X ->");

        yLabel.setText("Y ->");
        yLabel.setToolTipText("");

        xFromLabel.setText("FROM");

        yFromLabel.setText("FROM");

        xToLabel.setText("TO");

        yToLabel.setText("TO");
        yToLabel.setToolTipText("");

        buttonGroup1.add(pointRadioButton);
        pointRadioButton.setSelected(true);
        pointRadioButton.setText("Point");

        buttonGroup1.add(clusterRadioButton);
        clusterRadioButton.setText("Cluster");

        jLabel8.setText("Number:");

        generateButton.setText("Generate");
        generateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(shapeTypeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pointRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clusterRadioButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numberTextField))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(yLabel)
                                .addGap(18, 18, 18)
                                .addComponent(yFromLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yFromTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(xLabel)
                                .addGap(18, 18, 18)
                                .addComponent(xFromLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(xFromTextField)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(generateButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(xToLabel)
                                    .addComponent(yToLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(yToTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(xToTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shapeTypeLabel)
                    .addComponent(pointRadioButton)
                    .addComponent(clusterRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xFromLabel)
                    .addComponent(xFromTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xToLabel)
                    .addComponent(xLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xToTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yLabel)
                    .addComponent(yFromLabel)
                    .addComponent(yFromTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yToLabel)
                    .addComponent(yToTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(numberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void generateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButtonActionPerformed
        int cWidth = toolPanel.canvasPanel.getWidth();
        int cHeight = toolPanel.canvasPanel.getHeight();
        
        int selectedShape = pointRadioButton.isSelected() ? 0 : 1;

        String s = xFromTextField.getText();
        int fromX = (int) (HelperMethods.isNumeric(s) ? Double.parseDouble(s) : 20);

        s = xToTextField.getText();
        int toX = (int) (HelperMethods.isNumeric(s) ? Double.parseDouble(s) : cWidth - 80);

        s = yFromTextField.getText();
        int fromY = (int) (HelperMethods.isNumeric(s) ? Double.parseDouble(s) : 20);

        s = yToTextField.getText();
        int toY = (int) (HelperMethods.isNumeric(s) ? Double.parseDouble(s) : cHeight - 50);

        s = numberTextField.getText();
        int number = (int) (HelperMethods.isNumeric(s) ? Double.parseDouble(s) : 50);
        
        if(selectedShape == 0)
            toolPanel.canvasPanel.generateRandomPoints(fromX, fromY, toX, toY, number);
        else 
            toolPanel.canvasPanel.generateRandomClusters(fromX,fromY, toX, toY, number);
        
        JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        topFrame.setVisible(false);
    }//GEN-LAST:event_generateButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton clusterRadioButton;
    private javax.swing.JButton generateButton;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField numberTextField;
    private javax.swing.JRadioButton pointRadioButton;
    private javax.swing.JLabel shapeTypeLabel;
    private javax.swing.JLabel xFromLabel;
    private javax.swing.JTextField xFromTextField;
    private javax.swing.JLabel xLabel;
    private javax.swing.JLabel xToLabel;
    private javax.swing.JTextField xToTextField;
    private javax.swing.JLabel yFromLabel;
    private javax.swing.JTextField yFromTextField;
    private javax.swing.JLabel yLabel;
    private javax.swing.JLabel yToLabel;
    private javax.swing.JTextField yToTextField;
    // End of variables declaration//GEN-END:variables
}
